version: '3.4'

services:
  simple_ecommers_app.api:
    image: simpleecommersappapi:dev
    container_name: Simple_Ecommers_App.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Simple_Ecommers_App.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_simple_ecommers_app.api$
    volumes:
      - C:\Users\abdulazeez.adams\Desktop\Training\Docker\Simple_App\Simple_Ecommers_App.Api:/app
      - C:\Users\abdulazeez.adams\Desktop\Training\Docker\Simple_App:/src
      - C:\Users\abdulazeez.adams\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_simple_ecommers_app.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_simple_ecommers_app.api$ \"/app/bin/Debug/netcoreapp3.1/Simple_Ecommers_App.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true